site_author: EPAM Systems, Inc.
site_description: Hubctl is stack composition and lifecycle tool
site_name: Hubctl
site_url: https://hubctl.io

copyright: © 2023 EPAM Systems, Inc. All Rights Reserved.

repo_name: epam/hubctl
repo_url: https://github.com/epam/hubctl

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: cyan
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#automatic-hiding
    - header.autohide
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.instant
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-tracking
    - navigation.tracking
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
    - navigation.indexes
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy

extra:
  version:
    provider: mike

nav:
  - Home:
    - index.md
    - install.md
    - what-is.md
    - Use Cases: use-cases.md
  - Getting Started:
    - Basics:
      - tutorials/index.md
      - tutorials/010-hubctl-stack-init/README.md
      - tutorials/015-hubctl-stack-configure/README.md
      - tutorials/017-hubctl-stack-ls/README.md
      - tutorials/020-shell-component/README.md
    - Kubernetes:
      - tutorials/030-kubernetes-rancher-desktop/README.md
      - tutorials/035-redis-component/README.md
    - Terraform:
      - tutorials/040-aws-component/README.md
  - Reference documentation:
    - reference/index.md
    - Manifest files:
      - reference/manifests/index.md
      - Stack:
        - reference/manifests/stack/index.md
        - meta: reference/manifests/stack/meta.md
        - requires: reference/manifests/stack/requires.md
        - components: reference/manifests/stack/components.md
        - parameters: reference/manifests/stack/parameters.md
        - outputs: reference/manifests/stack/outputs.md
        - extensions: reference/manifests/stack/extensions.md
        - lifecycle: reference/manifests/stack/lifecycle.md
      - Component:
        - reference/manifests/component/index.md
        - meta: reference/manifests/component/meta.md
        - requires: reference/manifests/component/requires.md
        - provides: reference/manifests/component/provides.md
        - parameters: reference/manifests/component/parameters.md
        - templates: reference/manifests/component/templates.md
        - outputs: reference/manifests/component/outputs.md
    - Components:
        - reference/components/index.md
        - Terraform: reference/components/terraform.md
        - Kubernetes: reference/components/kubernetes.md
        - Helm: reference/components/helm.md
        - Kustomize: reference/components/kustomize.md
        - Shell: reference/components/shell.md
        - Makefile: reference/components/makefile.md
        - ARM: reference/components/arm.md
    - Configuration:
      - reference/design/index.md
      - reference/design/env.md
      - Domain Names: reference/design/dns.md
      - AWS: reference/design/aws.md
  - hubctl:
      # - Overview: hubctl/index.md
        - hubctl: hubctl/cli/index.md
        - hubctl stack: hubctl/cli/hubctl-stack.md
        - hubctl stack init: hubctl/cli/hubctl-stack-init.md
        - hubctl stack configure: hubctl/cli/hubctl-stack-configure.md
        - hubctl stack deploy: hubctl/cli/hubctl-stack-deploy.md
        - hubctl stack undeploy: hubctl/cli/hubctl-stack-undeploy.md
        - hubctl stack ls: hubctl/cli/hubctl-stack-ls.md
        - hubctl stack use: hubctl/cli/hubctl-stack-use.md
        - hubctl stack rm: hubctl/cli/hubctl-stack-rm.md
        - hubctl stack elaborate: hubctl/cli/hubctl-stack-elaborate.md
        - hubctl show: hubctl/cli/hubctl-show.md
        - hubctl toolbox: hubctl/cli/hubctl-toolbox.md
        - hubctl extensions: hubctl/cli/hubctl-extensions.md
        - hubctl extensions install: hubctl/cli/hubctl-extensions-install.md
        - hubctl extensions update: hubctl/cli/hubctl-extensions-update.md
        - hubctl ext: hubctl/cli/hubctl-ext.md
      #   - hubctl/design-and-architecture/index.md

plugins:
  - git-revision-date-localized
  - search:
      lang: en
