name: Documentation
on:
  issues:
    types: [opened, edited]
jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
    - uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.MICROSOFT_TEAMS_WEBHOOK_URI }}
        title: "@{{github.event.issue.actor}} {{github.event.issue.event}} issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}"
        summary: ${{ github.event.issue.body }}
        actions: '[{ "@type": "OpenUri", "name": "Link", "targets": [{ "os": "default", "uri": "${{ github.event.issue.url }}" }] }]'
