name: Issue Notification
run-name: "Notify #${{ github.event.issue.number }} ${{github.event.issue.event}}"
on:
  issues:
    types: [opened, edited, closed, reopened, assigned]
jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
    - uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
        title: "@${{github.event.issue.actor}} ${{github.event.issue.event}} issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}"
        text: ${{ github.event.issue.body }}
        actions: '[{ "@type": "OpenUri", "name": "Link", "targets": [{ "os": "default", "uri": "http://github.com/${{ github.event.repository.name }}/issues/${{ github.event.issue.number }}" }] }]'
